apiVersion: v1
kind: ConfigMap
metadata:
  name: data-sources
  namespace: $(service.namespace)$                        # stafftransfercore-[dev|qa|stag|prod]
data:
  appsettings.uat.json: |-
    {
      "AgencyData": {
        "User": "STAFFValhalla",
        "AgencyCode": "STAFF",
        "Password": "ST4FFV4llh4ll4",
        "Agency": "STAFF"
      },
      "OperacionesServiceApiClientOptions": {
        "BaseAddress": "$(app.operacionesServiceUrl)$"
      },
      "ValhallaApiClientOptions": {
        "BaseAddress": "$(app.addValhallaServiceApiUrl)$"
      },
      "Logging": {
        "IncludeScopes": true
        "LogLevel": {
          "Default": "Debug",
          "System": "Information",
          "Microsoft": "Information"
        }
      }
    }
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: $(app.name)$                                        # stafftransfercore
  namespace: $(service.namespace)$                          # stafftransfercore-[dev|qa|qa|prod]
spec:
  schedule: "*/30 * * * *"                                  # cada media hora
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: $(app.name)$                               # stafftransfercore
        spec:
          containers:
            - name: $(app.name)$                            # stafftransfercore
              image: $(imageContainer.url)$/$(image.name)$:$(Build.BuildId)$         # gcr.io/bdtg-shared-infra-prod/dmc/api/stafftransfercore:xxxx
              args: ["-it"]
              env:
              - name: ASPNETCORE_ENVIRONMENT
                value: production
              volumeMounts:
              - name: config-volume
                mountPath: /app/config
          volumes:
            - name: config-volume
              configMap:
                name: data-sources
          imagePullSecrets:
            - name: $(imageContainer.secret)$                # gcr-json-shared
          restartPolicy: Never
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
